export const ADD_PACKAGE = 'ADD_PACKAGE';
export const ADD_QUESTION = 'ADD_QUESTION';
export const REMOVE_PACKAGE = 'REMOVE_PACKAGE';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const MARK_ANSWER = 'MARK_ANSWER';
